### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Xyphenore** [george8188625/Create-Diesel-Generators#14]
**Describe the bug**

I got these warnings:

- Missing textures in model createdieselgenerators:biodiesel#level=3:minecraft:textures/atlas/blocks.png:createdieselgenerators:fluid/biodiesel_still
- Missing textures in model createdieselgenerators:plant_oil#level=15:minecraft:textures/atlas/blocks.png:createdieselgenerators:fluid/plant_oil_still
- Missing textures in model createdieselgenerators:ethanol#level=0:minecraft:textures/atlas/blocks.png:createdieselgenerators:fluid/ethanol_still

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.

**Additional context**
- Mod version: 1.1d for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by george8188625** [comment]
It will be fixed in the next version of the mod
