### ISSUE TITLE
Error for tag 'farmersdelight:tomato'

### ISSUE THREAD

**Issue by Xyphenore** [george8188625/Create-Diesel-Generators#15]
**Describe the bug**

When I create a world with the mod and without farmerdelight. I got this error:

Couldn't load tag [farmersdelight:tomato (from createdieselgenerators-1.20.1-1.1d.jar), farmersdelight:pumpkin_slice (from createdieselgenerators-1.20.1-1.1d.jar), farmersdelight:rice_panicle (from createdieselgenerators-1.20.1-1.1d.jar)] as it is missing following references: farmersdelight:tomato (from createdieselgenerators-1.20.1-1.1d.jar), 
	farmersdelight:pumpkin_slice (from createdieselgenerators-1.20.1-1.1d.jar), 
	farmersdelight:rice_panicle (from createdieselgenerators-1.20.1-1.1d.jar)

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world
- Error is printed on console

**Additional context**
- Mod version: 1.1d for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by george8188625** [comment]
It's a harmless little thing printed into the console, I will try to get it fixed in the next version of the mod
