### ISSUE TITLE
Please Add config for generator

### ISSUE THREAD

**Issue by SuddenlySentient** [george8188625/Create-Diesel-Generators#16]
the generators really suck by default. please add some config so you can change their speed, stress capacity, and fuel use rate

**Comment by FoxyFox909** [comment]
There already is a config that does all the things you listed, except fuel use rate.

This config can be found in a world's ``serverconfigs`` folder.

**Comment by george8188625** [comment]
fuel burn rate will be configurable in the next version of the mod
