### ISSUE TITLE
[1.20.1] Crash with newest Create Version

### ISSUE THREAD

**Issue by lays24mc** [george8188625/Create-Diesel-Generators#21]
Hi,

my game crashes when I install the newest Create version. 

Crashlog: https://pastebin.com/fJ05v1vB 

Mods:

Create 0.5.1.e 
Create: Diesel Geneartor 1.20.1-1.1d 
Forge 47.1.3

**Comment by george8188625** [comment]
try downgrading the create mod

**Comment by lays24mc** [comment]
With the Create Mod 0.5.1d it works. There should also be a hint message that it does not work with the new one :)

**Comment by Xyphenore** [comment]
There are any plans to support the 0.5.1e ?

**Comment by george8188625** [comment]
In the next version of the mod
