### ISSUE TITLE
Create v0.5.1e (issue)

### ISSUE THREAD

**Issue by billjk2013** [george8188625/Create-Diesel-Generators#23]
the create v0.5.1e update seems to have broken a few addon mods and this seems to be one is there a possibility of a version update to make it compatible with  v0.5.1e

**Comment by billjk2013** [comment]
[crash-2023-10-04_15.58.08-fml.txt](https://github.com/george8188625/Create-Diesel-Generators/files/12809985/crash-2023-10-04_15.58.08-fml.txt)
[latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/12809986/latest.log)

**Comment by george8188625** [comment]
Yeah it's a known issue that will get fixed in the next version
