### ISSUE TITLE
[1.19.2] Pondering about modular engines brings up the entry for engine silencers (and a couple other minor issues)

### ISSUE THREAD

**Issue by vizthex123** [george8188625/Create-Diesel-Generators#24]
It's so minor it's almost not worth reporting, but it did make me question if a scene was missing until I went to the next page and saw that there was an entry for the modular engine.

I also noticed that Plant Oil gives 48 RPM and 1,024 Stress Units even though it's really easy to get. I think having it being 32 RPM and 256 Stress Units would be a bit more balanced (or letting us configure each fluid rather than the vague "weak" and "strong" the config currently uses).

CraftTweaker support for fermenting basins and engines would also be lovely. CF page says nothing about it, so it seems like it's not implemented.

**Comment by george8188625** [comment]
You can configure the stress output in the server config, the modular diesel engine is already fixed and the fix will be here in the next version, you can already make custom recipe types, just like create processing recipes are made, I don't know if craft tweaker supports custom recipe types like kubejs but it should not you can just add that in a datapack

**Comment by vizthex123** [comment]
> You can configure the stress output in the server config, the modular diesel engine is already fixed and the fix will be here in the next version, you can already make custom recipe types, just like create processing recipes are made, I don't know if craft tweaker supports custom recipe types like kubejs but it should not you can just add that in a datapack

I'd _vastly_ prefer CraftTweaker support as I have never been able to make a datapack work in-game (especially since nobody ever tells you the damn format for how to change stuff from their mod) nor been able to even _begin_ to understand how tf KubeJS works (their docs are near-unreadable due to all the frontloading and it's annoying af).

But maybe I'm just a dumbass lol.

If the engine bug has been fixed already, that's fine. That and configs was why I made this report in the first place.

As I said though, you can't configure the stress or RPM output of each fluid _individually_ - just a vague "strong" and "weak" which covers all 3. Individual control is what I'd want in the config to better enforce the progression I'd like in my pack if you guys would be willing to add it.

**Comment by Nycto97** [comment]
@vizthex123 tip for KubeJS, don't use the docs only, use the repo code also. Like, there you can literally see all usable methods/functions etc.

**Comment by Nycto97** [comment]
And for the datapack approach, just look inside the mod how their data folder is set up and copy over what you would want to change, to a datapack. You can see the content of a .jar with WinRAR for example.
