### ISSUE TITLE
1.20.1 just fails

### ISSUE THREAD

**Issue by T342guy** [george8188625/Create-Diesel-Generators#25]
hi, i had wanted to add this mod to my server but got the same error on the server and client 

![Screenshot 2023-10-08 202926](https://github.com/george8188625/Create-Diesel-Generators/assets/147361653/b860b72a-e488-45f6-b5b2-9b6388ec690f)

**Comment by george8188625** [comment]
what create version are you playing on? If 0.5.1e then downgrade to 0.5.1d

**Comment by T342guy** [comment]
ohh ok, will say if does not work

**Comment by T342guy** [comment]
that fixed the issue, thx, 
also, in the next update are you going to fix this problem?

**Comment by george8188625** [comment]
Yup
