### ISSUE TITLE
Create Diesel Generators has failed to load correctly MC 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [george8188625/Create-Diesel-Generators#29]
MC 1.20.1
Forge: 47.2.1 
Create 0.5.1.e
![Screenshot_3](https://github.com/george8188625/Create-Diesel-Generators/assets/27385258/b4855ea9-28ca-41f0-9265-5e5ff414b243)

not sure if this will help speed things along or not to get it updated sooner.

here are the logs:

[crash report](https://mclo.gs/KcY9nLW)

[debug.log](https://mclo.gs/zWluqS9)

[latest.txt](https://mclo.gs/YSVXViD)

**Comment by george8188625** [comment]
downgrade to create 0.5.1d
