### ISSUE TITLE
Crash during multiblock diesel generator pondering

### ISSUE THREAD

**Issue by MindFaer** [george8188625/Create-Diesel-Generators#3]
Attached is the crash log for this. Crashes when pondering the multiblock diesel generator, and only the part when it attaches multiple generators to the back of the first one.

[crash-2023-07-19_15.01.55-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/12099272/crash-2023-07-19_15.01.55-client.txt)

**Comment by MrNavaStar** [comment]
yup I get the same thing on the latest release (1.20)

**Comment by PikachuGabe** [comment]
same issue but my log is a bit different, version 1.20.1-1.1b
[crash-2023-07-20_08.58.41-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/12111705/crash-2023-07-20_08.58.41-client.txt)
it seems some info is also present in logs, although only in the last few lines.

**Comment by george8188625** [comment]
the bug will be fixed in next update in a few days, it's just a simple NullPointerException
