### ISSUE TITLE
Client crash upon joining server - v1.2b

### ISSUE THREAD

**Issue by Nycto97** [george8188625/Create-Diesel-Generators#30]
[crash-2023-10-30_05.04.47-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13200619/crash-2023-10-30_05.04.47-client.txt)

**Comment by Nycto97** [comment]
Same happens in v1.2c

**Comment by george8188625** [comment]
it's probably some compat issue

**Comment by george8188625** [comment]
the mod causing this issue is dungeons libraries most likely, It's probably gonna get fixed in 1.2d

**Comment by Nycto97** [comment]
> the mod causing this issue is dungeons libraries most likely, It's probably gonna get fixed in 1.2d

Thanks for taking the time to look into this, much appreciated!

**Comment by Nycto97** [comment]
Seems like it is indeed Dungeons Libraries causing this, also still in v1.2d
[crash-2023-11-12_23.30.20-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13329348/crash-2023-11-12_23.30.20-client.txt)

**Comment by george8188625** [comment]
Oh, I'm gonna take a look into this more

**Comment by george8188625** [comment]
it should be fixed in 1.2e

**Comment by Nycto97** [comment]
> it should be fixed in 1.2e

Can confirm, thanks!
