### ISSUE TITLE
Pumpjack ponder structure is invalid

### ISSUE THREAD

**Issue by Obfus-8** [george8188625/Create-Diesel-Generators#31]
I couldn't get the pumpjack to work even by copying the ponder menu exactly so I "looked under the surface" a bit with NBTExplorer to make sure I had it right and still couldn't understand why it wasn't working. Finally just moved the central bearing over one block to make it balanced on both sides and it started right up. Seems like the dimensions are just wrong in the ponder menu, which is a little confusing.
![2023-10-30_02 37 07](https://github.com/george8188625/Create-Diesel-Generators/assets/25751719/01cfc97c-273c-407f-a07a-943526162364)
Left is modified, Right is the ponder nbt structure pasted in using a schematic

I'm on 1.20.1, mod version 1.2b, create version 0.5.1.e

**Comment by george8188625** [comment]
Everything is gonna be fixed in coming updates
