### ISSUE TITLE
Create Diesel Generators encountered error during sided_setup event pahse

### ISSUE THREAD

**Issue by Devilswarchild** [george8188625/Create-Diesel-Generators#32]
mc 1.20.1
forge 47.2.1
createdieselgenerators-1.20.1-1.2b

https://mclo.gs/L2cKWq5 - crash report.

another crash

(and no im not going to downgrade because 0.5.1.e of create fixes the deployers being broken and both my modpack and its officially hosted server need the fix.)

**Comment by george8188625** [comment]
that's not an issue with 0.5.1e, I know what's the issue, wait a day or two when I release the next version

**Comment by Devilswarchild** [comment]
alrighty
