### ISSUE TITLE
Please add config for fuels

### ISSUE THREAD

**Issue by Vilcu-Valentin** [george8188625/Create-Diesel-Generators#36]
By that I mean a way to configure the already existing fuels (gasoline, diesel, biodiesel etc.) to configure their speed, stress, burn rate.

Gasoline, diesel/biodiesel, have the same stats and it would be nice if they are changed or if you could modify them in the config. In real world they work a bit different, so you could make gasoline have a higher speed and burn rate, but lower stress, and the opposite for diesel/biodiesel.

**Comment by george8188625** [comment]
You can turn off ` forge:diesel `, ` forge:gasoline ` and ` forge:fuel ` in the configs, and add the ` createdieselgenerators:diesel_engine_fuel_[slow/fast]_[strong/weak]_[slow/fast]_burn ` tag to them I guess
