### ISSUE TITLE
Fermenting Timer doesn't Scale with Speed

### ISSUE THREAD

**Issue by CamKablam** [george8188625/Create-Diesel-Generators#37]
I am aware this may not be a direct issue in the mod, and may never become an issue, but I'm adding custom recipes for a modpack, and turning up the processing time makes the hand on the timer starts further.
It should start at the same place, but move at a slower speed

![2023-11-05_10 30 06](https://github.com/george8188625/Create-Diesel-Generators/assets/47013387/54ad6e57-6434-4fb5-93b5-eca0856fa157)
![2023-11-05_10 30 11](https://github.com/george8188625/Create-Diesel-Generators/assets/47013387/40694819-8291-49bd-9a9f-71d71365aab2)

**Comment by george8188625** [comment]
I'm aware of this issue, the rotation was supposed to be scaled, but there is an issue probably that the recipe duration is only on the server, not on the client
