### ISSUE TITLE
Adding milk as fuel doesn't add tooltip

### ISSUE THREAD

**Issue by Yarden-zamir** [george8188625/Create-Diesel-Generators#40]
![Screen Shot 2023-11-07 at 14 52 16](https://github.com/george8188625/Create-Diesel-Generators/assets/8178413/c9595731-0d2d-46e9-8cda-9ef042c17356)
![Screen Shot 2023-11-07 at 14 51 11](https://github.com/george8188625/Create-Diesel-Generators/assets/8178413/066ff14e-becd-43aa-9cd0-0f838f58f9a1)

**Comment by george8188625** [comment]
ah, milk bucket doesn't extend the ` BucketItem ` class
why would you make milk a fuel tho?

**Comment by Yarden-zamir** [comment]
Lol that's a valid question. I'm making a modpack where you have a milk powered spaceship and you crash land on a foreign planet. You then use the milk to produce energy using ships generators and also produce a lot of entry materials from milk.

Either way tho, is there a way to fix that? If not, is there a way to force the tool tip?

**Comment by george8188625** [comment]
I'll see if there is a way to fix that

**Comment by Yarden-zamir** [comment]
Awesome. Thank you

**Comment by Yarden-zamir** [comment]
@george8188625 this issue is back on 1.2e

**Comment by Yarden-zamir** [comment]
@george8188625 this issue is back on 1.2e

**Comment by george8188625** [comment]
I tested it tho Have you used the new fuel type system from 1.2e?

**Comment by Yarden-zamir** [comment]
No I did not, I didn't see there was one. Sorry, will check it out!
