### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by QianFuv** [george8188625/Create-Diesel-Generators#49]
https://mclo.gs/98wygd7

**Comment by QianFuv** [comment]
https://github.com/george8188625/Create-Diesel-Generators/issues/41

**Comment by QianFuv** [comment]
This crash is not happening **randomly**, but rather it happens **every time**. I have no choice but to **disable** this mod.
Log: https://mclo.gs/k4xocTT

Comment: I hope this can be resolved **as soon as possible**. This issue is **too critical**.

**Comment by QianFuv** [comment]
It seems like the crash won't happen again? It's strange, I'll open this issue again when the problem occurs once more.

**Comment by QianFuv** [comment]
Occasional crash. The most recent crash log: https://mclo.gs/UXxjZ4H

**Comment by george8188625** [comment]
I don't really know what causes this issue to be honest, at line 83 the sprite shifts are loaded and it says there is some hashmap error, I believe this is a flywheel error since that's where the crash points with the concurrent modification exeption

**Comment by QianFuv** [comment]
Thank you for your response. Should I report it to Flywheel or Create?

**Comment by george8188625** [comment]
don't report it yet, I'm gonna look into that issue more

**Comment by QianFuv** [comment]
Of course, I will always wait for your message.

**Comment by george8188625** [comment]
that's something I can't really fix, if 2 mods register the sprite shifts at the exact same time the crash happens

**Comment by QianFuv** [comment]
Can you adjust the registration order to make compatibility? Or there's another way

**Comment by george8188625** [comment]
when I did it later sometimes the connected textures didn't work, I can't register it before it already is

**Comment by QianFuv** [comment]
Do you know what another mod that registers with sprite shifts is?

**Comment by george8188625** [comment]
any mod that uses creates connected textures

**Comment by QianFuv** [comment]
So, there's a really interesting question here. If I install more than one mod of this type (in fact, I should have installed more than one), why don't they conflict with each other?

**Comment by QianFuv** [comment]
https://www.curseforge.com/minecraft/mc-mods/create-deco
https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear
https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails

I know of these three mods, there may be more. I have a modpack with over 500 mods.

**Comment by george8188625** [comment]
> So, there's a really interesting question here. If I install more than one mod of this type (in fact, I should have installed more than one), why don't they conflict with each other?

I don't really know, it's happening at random, but it's weird that it only starts happening with c:dg, I don't have any other explanation as the ConcurrentModificationExeption happens when a map is modified at the same time, which only can be done by two mods registering these sprite shifts at the same time. I use many mods using creates connected textures and I've never got an error like that

**Comment by QianFuv** [comment]
So there's no way to solve it?

**Comment by george8188625** [comment]
Most likely I can't do anything to fix it

**Comment by QianFuv** [comment]
Well, I'm sorry to have to give up adding this mod to my modpack.
