### ISSUE TITLE
Sound of Diesel engines is extremely obnoxious and way too loud

### ISSUE THREAD

**Issue by burdoto** [george8188625/Create-Diesel-Generators#50]
title has the core of it

yes i understand it should be loud, but this is way too much. i have to turn block sounds down to 5% to notice ANY difference.
please either add some other option to silence it other than this weird silencer item, or at least make the sound less obnoxious. this is hostile by design.

yes theres a silencer item, however it doesnt seem to work with huge diesel engines

i've had many users on our server complain about it, getting overstimulated. this sound is an autism killer.

**Comment by burdoto** [comment]
honestly after the amount of users who have complained about it, this should either be fixed or the mod is out of the pack.

**Comment by NaveNosliv** [comment]
Major issues with audio breaking and overlapping itself. almost game breaking without having to turn audio off. great mod, but come on.

**Comment by george8188625** [comment]
How is it breaking tho

**Comment by george8188625** [comment]
> Major issues with audio breaking and overlapping itself. almost game breaking without having to turn audio off. great mod, but come on.

Feel free to make your own sounds in a resource pack (if you like more there is an ogg file with _old in the sound directory that is a bit different)
