### ISSUE TITLE
Compatibility issues with train mod KuaYue

### ISSUE THREAD

**Issue by YaogouYuki** [george8188625/Create-Diesel-Generators#52]
Game version: 1.18.2
Forge version: 40.2.14
Problem mod version：0.1.1~0.3.5

Issue details:

Normally run Create, Create: Diesel Generators and KuaYue will cause the game to fail to start
In development mode, running only Create: Diesel Generators and KuaYue did not crash, but adding Create would cause the game to crash

Problem mod link:

KuaYue:[https://modrinth.com/mod/kuayue/versions?g=1.18.2](url)

Problem analysis:

Inject this annotation does not find a method to execute
<img width="151" alt="6X7 }RAG(RR@60H9XMMPKL" src="https://github.com/george8188625/Create-Diesel-Generators/assets/91942344/71df0b79-8444-4afb-b9fe-08a8293aa852">

debug.log:

https://mclo.gs/uj6L5Bi

latest.log:

https://mclo.gs/FVxS8iy

**Comment by YaogouYuki** [comment]
In fact, the KuaYue team says they don't use itemStack related code

**Comment by HTony03** [comment]
in detail:
 kuayue mod has not used or any mixin modification on the tick() method in the itemstack, but this would happen whenever adding kuayue and the mod would cause:

`Mixin apply failed createdieselgenerators.mixins.json:EntityMixin -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on tick could not find any targets matching 'tick()V' in net.minecraft.world.entity.Entity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> createdieselgenerators.mixins.json:EntityMixin -> Prepare Injections ->  -> handler$emg007$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on tick could not find any targets matching 'tick()V' in net.minecraft.world.entity.Entity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> createdieselgenerators.mixins.json:EntityMixin -> Prepare Injections ->  -> handler$emg007$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} `
We’ve discussed about this problem and it seems like the mixin ver was not the same and used the wrong method

**Comment by george8188625** [comment]
It's gonna get fixed in 1.2g, I've already solved this issue

**Comment by george8188625** [comment]
And yes I've changed the mixin to inject into entity
