### ISSUE TITLE
Compatibility issues with multiplayer game

### ISSUE THREAD

**Issue by Cynical1115** [george8188625/Create-Diesel-Generators#53]
Game version: 1.20.1
Forge version: 47.2.14
Problem mod version：1.2e

Issue details:
The pumpjack couldn't work correctly in multiplayer game.It has animation and sound effects, but it just doesn't work.

**Comment by george8188625** [comment]
did you make sure you built the pumpjack correctly in an oil chunk, with an open output on the copper casing with a pump pulling out of it?
also last time I checked pumpjacks didn't have sound effects _(yet)_

**Comment by Cynical1115** [comment]
Sorry, my mistake. What I want to say is actually diesel engines. To be precise, this issue is caused by both this MOD and Mekanism MOD(Both versions are up-to-date). When I installed both on the server, all types of diesel engines no longer work.

**Comment by george8188625** [comment]
Oh so it just doesn't work on the server side as the animation and sounds are on the client side, that's wierd as the fuel types are on the server

**Comment by Cynical1115** [comment]
When I installed this mod alone, the diesel engine was running normally, but when I installed Mekanism, even the original working diesel engine stopped working.
I use diesel, which is a supported fuel in JEI

**Comment by V3rt3x824** [comment]
I seem to be having the same issue on 1.18.2. haven't checked if Mekanism is the cause, but it is in the pack and this is the exact issue i am facing on a multiplayer server
