### ISSUE TITLE
Video on how to add the data pack for fuel configuration 

### ISSUE THREAD

**Issue by ChiefEhoy19** [george8188625/Create-Diesel-Generators#55]
Really confusing trying to get it to work and almost nothing on the internet

**Comment by Yarden-zamir** [comment]
Have a file that looks like this
data/createdieselgenerators/diesel_engine_fuel_types/milk.json
```json
{
  "fluid": "#forge:milk",
  "sound_speed": 8,
  "normal": {
    "speed": 16.0,
    "strength": 1024.0,
    "burn_rate": 2
  },
  "modular": {
    "speed": 16.0,
    "strength": 1024.0,
    "burn_rate": 2
  },
  "huge": {
    "speed": 8.0,
    "strength": 1024.0,
    "burn_rate": 3
  }
}
```

The data folder is as a datapack or if you have kubejs, their data folder acts as a datapack too so
`kubejs/data/createdieselgenerators/diesel_engine_fuel_types/milk.json`

**Comment by Yarden-zamir** [comment]
The documentation is here
https://github.com/george8188625/Create-Diesel-Generators/wiki/Customization#adding-custom-fuel-types

**Comment by Yarden-zamir** [comment]
@george8188625 I added a link to the wiki in the readme if you want 
https://github.com/george8188625/Create-Diesel-Generators/pull/57

**Comment by ChiefEhoy19** [comment]
Thank you for your help kubejs was a big help

**Comment by ChiefEhoy19** [comment]
How do you tell what the #forge part for different mods

**Comment by ChiefEhoy19** [comment]
Mainly Create:The Factory Must Grow it has its own gasoline and diesel

**Comment by george8188625** [comment]
` #forge:gasoline ` is a fluid tag, mods should use these tags when they are making stuff like this, tags are like groups of fluids and mods should add their fluids to these tags, ` createdieselgenerators:gasoline ` is a specific fluid from a mod
For some reason last time I checked tfmg doesn't use these tags, that's why it's not compatible with many mods

**Comment by Yarden-zamir** [comment]
@ChiefEhoy19 if you check the fluid id that they are using, you can put it there without the #

**Comment by Yarden-zamir** [comment]
@ChiefEhoy19 if you check the fluid id that they are using, you can put it there without the #

**Comment by ChiefEhoy19** [comment]
All it was is was tfmg:diesel thanks for the help
