### ISSUE TITLE
[Bug/Crash] [1.20.1] [47.1.39] Crashing when pondering

### ISSUE THREAD

**Issue by CathieNova** [george8188625/Create-Diesel-Generators#6]
I'm running a server and one of the people playing crashes when he ponders the "modular diesel engine", i'll copy paste his message here with his crash report.

`I got this Crash Report while pondering the modular diesel engine, it crashed specifically at the step you can jump to where it says you can stack them. exactly upon reaching the marker in the timeline the game crashed. also this is the text of the popup the launcher gave me as well for the same crash.`

`The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Cannot read field "tank" because "this.FrontEngine" is null`

https://pastebin.com/sKXkRpJ7 <-- crash log

**Comment by george8188625** [comment]
is this person on the latest version of the mod?

**Comment by CathieNova** [comment]
This is on version 1.20.1-1.1b

Edit: i noticed there was an update (1.1c) and it works there.
