### ISSUE TITLE
[1.18.2] Client crashes while pondering item

### ISSUE THREAD

**Issue by NeroWT** [george8188625/Create-Diesel-Generators#60]
When pondering the `Diesel engine` item, the client crashes with the error code:

`java.lang.NullPointerException: Cannot invoke "com.jesz.createdieselgenerators.other.CDGFuelType.getGeneratedNormal()" because the return value of "com.jesz.createdieselgenerators.other.FuelTypeManager.getType(net.minecraft.world.level.material.Fluid)" is null`

**Comment by Nycto97** [comment]
Also happens on 1.19.2, reported in #58

**Comment by NeroWT** [comment]
> Also happens on 1.19.2, reported in #58

Yes, i had read it but because it happened on 1.19.2 i thought i'd report the issue with the version i was working with (1.18.2)

**Comment by NeroWT** [comment]
Update: As of 2/1/2024 i've just noticed that the Modular engine also crashes the game, it seems as if loading/rendering a modification in kinetic speed because of the create mod makes the game crash client-wise

```
Suspected Mods: 
	Create Diesel Generators (createdieselgenerators), Version: 1.18.2-1.2f
		at TRANSFORMER/createdieselgenerators@1.18.2-1.2f/com.jesz.createdieselgenerators.ponder.DieselEngineScenes.lambda$small$5(DieselEngineScenes.java:87)

	Create (create), Version: 0.5.1.b
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@0.5.1.b/com.simibubi.create.foundation.ponder.SceneBuilder$WorldInstructions.lambda$modifyKineticSpeed$30(SceneBuilder.java:783)
```

**Comment by george8188625** [comment]
Next version should fix that. I imagine huge engines crash too
