### ISSUE TITLE
Server crashed when ever we fire using chemical sprayer

### ISSUE THREAD

**Issue by Deblin-Mallick** [george8188625/Create-Diesel-Generators#64]
Server crashed when ever we use this Item "Chemical Sprayer"
[crash-2024-01-02_15.41.51-server.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13826754/crash-2024-01-02_15.41.51-server.txt)

**Comment by george8188625** [comment]
Try the latest version of the mod
