### ISSUE TITLE
Stress unit dupe???? (1.20.1 forge)

### ISSUE THREAD

**Issue by DaPuffer** [george8188625/Create-Diesel-Generators#65]
So i have this test contraption that automatically powers itself,the creative tank has infinite diesel.
![2024-01-04_18 06 00](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/201c5895-8bd1-4c91-a79c-2353e499355d)
![2024-01-04_18 06 05](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/ac1eac69-c107-4307-880c-19f3acd089ed)
![2024-01-04_18 06 08](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/177574c7-04b2-48b1-b37b-8052d7a0e0f7)
both goggles and the stressometer say it produces 20k stress units. 
![2024-01-04_18 06 27](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/6b22ded5-cf79-44e1-9fb9-2cdc1253ade6)
but after rejoining the world,it suddenly becomes 40k? it does not show up on the modular diesel engine with goggles
![2024-01-04_18 09 17](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/02e4c74c-5a73-42cf-b14a-964732d5754d)
 on the goggles,but i can connect a lot more to it without it getting overstressed
[latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/13829646/latest.log)
[debug.log](https://github.com/george8188625/Create-Diesel-Generators/files/13829647/debug.log)

**Comment by DaPuffer** [comment]
i haven't seen anything like this before.
![image](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/a95b30ec-c0eb-4116-92f9-d751bbef4493)
here's the mod list,just in case.

**Comment by DaPuffer** [comment]
Also happens with just create and diesel generators. you have to break and place the stressometer for it to update though

**Comment by DaPuffer** [comment]
*also* happens with regular engines connected to eachother

**Comment by DaPuffer** [comment]
> Also happens with just create and diesel generators. you have to break and place the stressometer for it to update though

![2024-01-04_19 10 05](https://github.com/george8188625/Create-Diesel-Generators/assets/132820752/005c5ec1-06d7-459d-95a4-08efd9e86fa1)
a single engine powering THIS ENTIRE PUMPJACK CENTIPEDE

**Comment by DaPuffer** [comment]
It stopped at 100% stress usage,silencers stopped working. decided to disconnect the centipede and rejoin and uh...
[latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/13830167/latest.log)

**Comment by DaPuffer** [comment]
> It stopped at 100% stress usage,silencers stopped working. decided to disconnect the centipede and rejoin and uh... [latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/13830167/latest.log)

the silencers just don't work now on regular engines,latest create and diesel generators version

**Comment by george8188625** [comment]
> > It stopped at 100% stress usage,silencers stopped working. decided to disconnect the centipede and rejoin and uh... [latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/13830167/latest.log)
> 
> the silencers just don't work now on regular engines,latest create and diesel generators version

I'm aware of silencers not working. The fact that the engines make twice as much su is absolutely crazy and I do not know how it's possible, but I'm gonna take a look into that.

**Comment by DaPuffer** [comment]
> > > It stopped at 100% stress usage,silencers stopped working. decided to disconnect the centipede and rejoin and uh... [latest.log](https://github.com/george8188625/Create-Diesel-Generators/files/13830167/latest.log)
> > 
> > 
> > the silencers just don't work now on regular engines,latest create and diesel generators version
> 
> I'm aware of silencers not working. The fact that the engines make twice as much su is absolutely crazy and I do not know how it's possible, but I'm gonna take a look into that.

actually,duplication is not the right word. it just adds the base su each rejoin. rejoin 1: su. rejoin 2: x2 su rejoin 3. x3 su etc

**Comment by DaPuffer** [comment]
another thing: if the system is overstressed,rejoining will only lower the stress usage untill 100%. after that,su duplcation stops

**Comment by Yarden-zamir** [comment]
This issue is reproduced on create prepare to dye modpack for all of our players too

**Comment by AEtherington** [comment]
This issue is also prevalent in the upcoming FTB Skyblock Expert pack

**Comment by DatenThielt** [comment]
This issue is also prevalent in the upcoming FTB Skyblock Expert pack

**Comment by george8188625** [comment]
I think I fixed it, this issue is gonna be gone in the next version of the mod

**Comment by DatenThielt** [comment]
Sounds great, I will add this might be more related to updating the SU network, than it actually duping,  As if I have standard mod create items connected, and I break/replace  the SU network updates and everything is normal, Hopefully part of your fix :)

**Comment by george8188625** [comment]
yeah, that was related to updating the generated rotation

**Comment by Saereth** [comment]
Any idea when you'll have a chance to push a release build on this?

**Comment by george8188625** [comment]
When it's done, probably a few days

**Comment by Saereth** [comment]
Sounds good, and I wasn't trying to press you for an eta or anything but we have our own deadlines and have to plan for inclusion of mods into our packs according ot those deadlines so after this weekend we'll have to make a decision on that one way or another as this is a breaking bug. Thanks for the followup though, and no worries!

**Comment by TheBlckbird** [comment]
this bug still exists for me. I am using the newest version of this mod. Is the patch already merged and released?
