### ISSUE TITLE
Compatibility issue with CC:C Bridge

### ISSUE THREAD

**Issue by lonevox** [george8188625/Create-Diesel-Generators#66]
Game version: 1.20.1
Forge version: 47.2.0

This looks to be a similar problem to #52. The game crashes on launch with a mixin error if both Create Diesel Generators and CC:C Bridge are installed. Here's the logs: https://mclo.gs/JJEtiNq

**Comment by george8188625** [comment]
That's not a compat issue with c:cc bridge, his is a known issue I'm working on fixing, I launched both on 1.20.1 and everything worked fine
For now you can fix the issue on your side https://github.com/george8188625/Create-Diesel-Generators/issues/59#issuecomment-1870702166 but a feature is gonna be missing
