### ISSUE TITLE
1.18.2 crash in Ponder

### ISSUE THREAD

**Issue by SGZ-Creations** [george8188625/Create-Diesel-Generators#69]
Crash with Exit code: -1
[crash-2024-01-20_22.59.45-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13999318/crash-2024-01-20_22.59.45-client.txt)

**Comment by george8188625** [comment]
should be fixed now

**Comment by SGZ-Creations** [comment]
Thanks
