### ISSUE TITLE
[1.18.2] Client crash while playing

### ISSUE THREAD

**Issue by NuoranDFDG** [george8188625/Create-Diesel-Generators#71]
game mod with errors, as follows:
- **create-diesel-generators-1.18.2-1.2f**
- valkyrienskies-118-forge-2.1.1-beta.6+b1ee932637
- create_interactive-forge-1.0.0-beta.1+fead03adaf
- create-1.18.2-0.5.1.f

game crash log: [crash-2024-01-31_00.53.41-server.txt](https://github.com/george8188625/Create-Diesel-Generators/files/14102043/crash-2024-01-31_00.53.41-server.txt)
When I structure the train, if there are **Huge Diesel Engines**  above the train, the game will crash.

![2024-01-31_01 40 53](https://github.com/george8188625/Create-Diesel-Generators/assets/106331191/4952fd00-e296-46d8-8bbc-ec5b2644fe79)

After the game crashes and I re-enter the map, the game still crashes.

If **Huge Diesel Engines** is placed on a already structured train, the game will also crash.

**Comment by george8188625** [comment]
It's gonna get fixed in 1.2g

**Comment by george8188625** [comment]
should be fixed
