### ISSUE TITLE
Unsafe capability cast

### ISSUE THREAD

**Issue by MehVahdJukaar** [george8188625/Create-Diesel-Generators#74]
here https://github.com/george8188625/Create-Diesel-Generators/blob/47672f012891e5faacb6ce6a8f8bc0aa5bef929f/src/main/java/com/jesz/createdieselgenerators/blocks/entity/HugeDieselEngineBlockEntity.java#L171

**Comment by george8188625** [comment]
I'm aware of that, it's gonna get fixed soon
