### ISSUE TITLE
Turning off a modular engine with a redstone signal bricks the engine until you break and replace

### ISSUE THREAD

**Issue by Saereth** [george8188625/Create-Diesel-Generators#76]
If you use a lever and give a redstone signal to a modular diesel engine it will turn off but remove the redstone signal will not turn it back on. Create goggles show no SU/Network data. 

version: createdieselgenerators-1.19.2-1.2h.jar
MC 1.19.2 
forge: 43.3.7

**Comment by Tursiops-G** [comment]
Try adding redstone dust so that ALL the engines get a redstone control signal.
