### ISSUE TITLE
[Suggestion] Fermentation Indication

### ISSUE THREAD

**Issue by MythrilBagels** [george8188625/Create-Diesel-Generators#8]
Hi! Loving this mod so far, the basin fermenting is very cute and elegant, however there is something I would like to suggest.

# Here is my suggestion
Similarly to noises the mixer or press make when they are working, perhaps the Fermenting Basin could have a sort of bubbling sound to tell the player that it is working.

I am planning on using the fermenting basin for some far longer recipes, and I want players to be able to tell if it's actually making them or not, since currently there is no indication.

### Here's what I personally have in mind:
- When the Basin Lid is open, no sounds play.
- When the Basin Lid is closed, but the items or fluids inside cannot be processed, no sounds play.
- When the Basin Lid is closed, and the items or fluids inside can be processed, then a periodic bubbling sound will play throughout the process, similarly to the crackling of a furnace.
- When the processing is finished, an exaggerated bubbling sound plays, letting the player know that it has finished.

I can imagine this being a very positive ambient addition. Imagine a factory filled with fermenting basins, all lightly bubbling away as they process whatever is inside them.

### - Sincerely, a fermentation aficionado

**Comment by george8188625** [comment]
that is an amazing idea
